version: '2'

services:
  clarus:
    image: clarus/proxy
    networks:
        - front-tier
        - back-tier
    environment:
        CLOUD_IP: "pg-master"
        CLOUD_PORT: "5432"
        SECURITY_POLICY: "/etc/clarus/security-policy/patient_anonymisation.xml"
    volumes:
        - ./clarus/securitypolicies:/etc/clarus/security-policy/:ro
    ports:
        - 5432:5432
  pg-master:
    build: '.'
    image: 'danieldent/postgres-replication'
    restart: 'always'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'password'
      PGDATA: '/var/lib/postgresql/data/pgdata'
    volumes:
     - '/var/lib/postgresql/data'
    ports:
        - 5433:5432
    networks:
        - back-tier
    depends_on:
        - clarus

  pg-slave:
    build: '.'
    image: 'danieldent/postgres-replication'
    restart: 'always'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'password'
      PGDATA: '/var/lib/postgresql/data/pgdata'
      REPLICATE_FROM: 'pg-master'
    volumes:
     - '/var/lib/postgresql/data'
    expose:
     - '5432'
    links:
     - 'pg-master'
    networks:
        - back-tier
    depends_on:
        - pg-master
networks:
    front-tier: 
      driver: bridge
      ipam:
        config:
            - subnet: 10.10.6.0/24
    back-tier: 
      driver: bridge
      ipam:
        config:
            - subnet: 10.10.7.0/24
