version: '2'
services:
  clarus1:
    image: clarus/proxy
    links:
        - postgres
    networks:
        - front-tier
    environment:
        CLOUD_IP: "postgres"
        CLOUD_PORT: "5432"
        SECURITY_POLICY: "/etc/clarus/security-policy/searchable_encryption.xml"
  postgres:
    build: ./postgres
    restart: always
    environment: 
        POSTGRES_USER: "postgres"
        POSTGRES_PASSWORD: "password"
    networks:
        - back-tier
    ports:
        - 1234:5432
networks:
    front-tier:
      driver: bridge
      ipam:
        config:
            - subnet: 10.10.1.0/24
    back-tier:
      driver: bridge
      ipam:
        config:
            - subnet: 10.10.2.0/24
